SELECT MTX_JAM_STAT_DATA.HANDLERNAME, MTX_JAM_STAT_DATA.WEEK, MTX_JAM_STAT_DATA.ALARMTEXT, MTX_JAM_STAT_GROUPINGS.GROUPID,  COUNT(MTX_JAM_STAT_DATA.ALID) AS COUNT 
FROM MTX_JAM_STAT_DATA 
LEFT JOIN MTX_JAM_STAT_GROUPINGS ON MTX_JAM_STAT_GROUPINGS.ALID = MTX_JAM_STAT_DATA.ALID 
WHERE HANDLERNAME = 'MTXA05' AND WEEK BETWEEN 1 AND 26 
GROUP BY MTX_JAM_STAT_GROUPINGS.GROUPID, MTX_JAM_STAT_DATA.HANDLERNAME, MTX_JAM_STAT_DATA.WEEK, MTX_JAM_STAT_DATA.ALARMTEXT
ORDER BY MTX_JAM_STAT_DATA.WEEK DESC